@startuml AD1_1.0
skinparam maxMessageSize 100
left header
    <font color=000 size=18><b>Package:</b> AD1_1.0
end header

legend top left
    <b>ID:</b> UC_2
    <b>Назва:</b> Перегляд доступних маршрутів
    <b>Учасники:</b> Пасажир, Форма, Менеджер, БД
    <b>Результат:</b> Список маршрутiв
endlegend

|Пасажир|
start
: Обрати параметри маршруту;

|Форма\nпошуку\nмаршруту|
: Передати iнформацiю\nпро параметри маршруту;

|Менеджер\nпошуку\nмаршрута|
: Знайти маршрути\nза вказаними параметрами;

|База\nданих\nкомпанiї|
: Пошук маршрутiв\nза вказаними параметрами;

|Менеджер\nпошуку\nмаршрута|
: Вiдобразити список\nнаявних квиткiв;

|Форма\nпошуку\nмаршруту|
: Вiдобразити список\nнаявних квиткiв;

|Пасажир|
stop;

right footer
    Програмний продукт для складання подорожей.
    Дiаграма активностi.
    НТУУ КПІ ім.І.Сікорського
    Голубов Iван
    Київ-2023
end footer
@enduml