@startuml AD2_1.0

skinparam maxMessageSize 100
left header
    <font color=000 size=18><b>Package:</b> AD2_1.0
end header

legend top left
    <b>ID:</b> UC_1
    <b>Назва:</b> Придбання квитка
    <b>Учасники:</b> Пасажир, Форма, Менеджер, БД, Квитки
    <b>Результат:</b> Квиток пасажира
endlegend

|Пасажир|
start
:Обирати маршрут;

|#AntiqueWhite|Форма\nобрання\nквитка|
:Передати iнформацiю\nпро маршрут (SD1_1.0);

|#Lavender|Менеджер\nпридбання\nквитка|
:Знайти квитки;

|#APPLICATION|База\nданих\nкомпанiї|
:Пошук квиткiв;

|Менеджер\nпридбання\nквитка|
:Передати знайденi квитки;

|Форма\nобрання\nквитка|
:Вiдобразити список\nнаявних квиткiв;

|Пасажир|
:Обрати квиток;
|Форма\nоплати\nквитка|
fork 
    #Khaki:Запросити iнформацiю\nпро карту оплати;
    |Пасажир|
    #Khaki:Ввести iнформацiю\nпро карту оплати;
    |#Moccasin|Форма\nоплати\nквитка|
    #Khaki:Передати iнформацiю\nпро карту оплати;

fork again
    |Форма\nоплати\nквитка|
    #Plum:Передати номер квитка;
    |Менеджер\nпридбання\nквитка|
    #Plum:Знайти квиток\nза номером;
    |База\nданих\nкомпанiї|
    #Plum:Пошук квитка\nза номером;
    |Менеджер\nпридбання\nквитка|
    #Plum:Передати iнформацiю\nпро квиток\nза номером;
    |Форма\nоплати\nквитка|
end fork
|Менеджер\nпридбання\nквитка|
:Оплата квитка;
if (Оплата успiшна?) then (yes)
    #palegreen:Зв'язати знайдений\nквиток з пасажиром;
    |База\nданих\nкомпанiї|
    :Оновити iнформацiю\nпро квиток;
    |Форма\nоплати\nквитка|
    if (Оновлення успiшне?) then (yes)
        #palegreen:Вiдобразити iнформацiю квитка;
    else (no)
        #pink:Вiдобразити помилку оновлення;
    endif
else (no)
    #pink:Вiдобразити помилку оплати;
endif
|Пасажир|
stop;

right footer
    Програмний продукт для складання подорожей.
    Дiаграма послiдовностi.
    НТУУ КПІ ім.І.Сікорського
    Голубов Iван
    Київ-2023
end footer

@enduml
