@startuml GD_1.0
title
<font size=18 color=black>Програмний продукт для складання подорожей
end title
Project starts 2023-09-01
[T1] starts 2023-09-01
[T7] starts 2023-09-01
[T1] lasts 14 days and is colored in LightBlue/Black
[T7] lasts 2 days and is colored in LightCoral/Black 
[M1] happens at [T1]'s end



[T2] starts at [T1]'s end
[T2] lasts 10 days and is colored in LightGreen/Black
[T3] starts at [T1]'s end
[T3] lasts 10 days and is colored in LightPink/Black
[T4] starts at [T1]'s end
[T4] lasts 10 days and is colored in Yellow/Black
[T5] starts at [T1]'s end
[T5] lasts 5 days and is colored in LightBlue/Black
[M2] happens at [T2]'s end
[T6] starts at [T2]'s end
[T6] lasts 14 days and is colored in LightGreen/Black

[M3] happens at [T7]'s end
[T8] starts at [T7]'s end
[T8] lasts 5 days and is colored in LightCoral/Black 
[T9] starts at [T8]'s end
[T9] lasts 5 days and is colored in LightCoral/Black 
[T10] starts at [T9]'s end
[T10] lasts 5 days and is colored in LightCoral/Black 
[T11] starts at [T10]'s end
[T11] lasts 5 days and is colored in LightCoral/Black 



[M4] happens at [T6]'s end
[T12] starts at [M4]'s end
[T11] lasts 5 days and is colored in LightCoral/Black 
[T12] lasts 2 days and is colored in LightCoral/Black 

[M5] happens at [T12]'s end
[T13] starts at [M5]'s end
[T13] lasts 3 days
[T13.1] starts at [M5]'s end
[T13.1] lasts 1 days and is colored in LightBlue/Black
[T13.2] starts at [M5]'s end
[T13.2] lasts 1 days and is colored in LightGreen/Black
[T13.3] starts at [M5]'s end
[T13.3] lasts 1 days and is colored in LightCoral/Black
[Кiнець] happens at [T13]'s end
legend left
|= Name |= Color |
| Ivan |<#LightBlue>|
| Max |<#LightGreen>|
| Diana |<#LightPink>|
| Anatolii |<#Yellow>|
end legend 
right footer
    Програмний продукт для складання подорожей.
    Дiаграма Ганта
    НТУУ КПІ ім.І.Сікорського
    Голубов Iван
    Київ-2023
end footer

@enduml