@startuml T_5.1
title
<font size=18 color=black>Програмний продукт для складання подорожей
end title
storage "Початок" as start_name
storage "Кiнець" as end_name
rectangle "T1\n(14 днiв)" as T1 #White
rectangle "T2\n(10 днiв)" as T2 #White
rectangle "T3\n(10 днiв)" as T3 #White
rectangle "T4\n(10 днiв)" as T4 #White
rectangle "T5\n(4 дня)" as T5 #White
rectangle "T6\n(14 днiв)" as T6 #White
rectangle "T7\n(2 дня)" as T7 #White
rectangle "T8\n(5 днiв)" as T8 #White
rectangle "T9\n(5 днiв)" as T9 #White
rectangle "T10\n(5 днiв)" as T10 #White
rectangle "T11\n(5 днiв)" as T11 #White
rectangle "T12\n(2 дня)" as T12 #White
rectangle "T13\n(3 дня)" as T13 #White
storage "M1\n14/09/23" as M1 #White
storage "M2\n24/09/23" as M2 #White
storage "M3\n02/09/23" as M3 #White
storage "M4\n08/10/23" as M4 #White
storage "M5\n10/10/23" as M5 #White

start_name--T1
T1--M1
M1--T2
M1--T3
M1--T4
M1--T5
T2--M2
T3--M2
T4--M2
T5--M2
M2--T6
start_name--T7
T7--M3
M3--T8
M3--T9
M3--T10
M3--T11
T6--M4
T8--M4
T9--M4
T10--M4
T11--M4
M4--T12
T12--M5
M5--T13
T13--end_name

right footer
    Програмний продукт для складання подорожей.
    Мережна діаграма етапів
    НТУУ КПІ ім.І.Сікорського
    Голубов Iван
    Київ-2023
end footer

@enduml
/'
Т1 Проєктування БД  14 
Т2 Створення мікросервісу для реєстрації та аутентифікації 7-14 Т1 (М1)
T3 Створення мікросервісу для CRUD маршрутiв 7-14 Т1 (М1)
Т4 Створення мікросервісу для придбання квитка 7-14 Т1 (М1)
T5 Перегляд доступних квиткiв 3-5 T1 (M1)
T6 Розробка API Gateway 7-14 Т2, Т3, Т4, Т5 (М2)
Т7 Створення стилю для WEB-інтерфейсу 1-2
T8 Розробка WEB-сторiнки реєстрації та аутентифікації 3-7  Т7(М3) 
Т9 Розробка WEB-сторiнки профiля пасажира 3-7 Т7(М3) 
Т10 Розробка WEB-сторiнки пошуку маршрута 3-7 Т7(М3) 
Т11 Розробка WEB-сторiнки придбання квитка 3-7 Т7(М3) 
Т12 Об'єднання WEB-сторiнок у єдиний сайт 1-2 T8, T9, T10, T11 (M4)
Т13 Тестування 3 Т1, Т6, T12 (M5)
/'