@startuml UCD_1.0

right header
    <font size=24 color=black>Package: <b>UCD_1.0

end header

title
<font size=18 color=black>Програмний продукт для складання подорожей
end title

actor "Пасажир"  as User #lightBlue
actor "Адміністратор" as Admin #LightYellow

usecase "<b>UC_1</b>\nПридбання квитка" as UC_1  #lightBlue
usecase "<b>UC_2</b>\nПерегляд доступних\nмаршрутів" as UC_2  #lightBlue
usecase "<b>UC_1.1</b>\nНарахування бонусів" as UC_1.1 #LightYellow
usecase "<b>UC_1.2</b>\nСписання бонусів" as UC_1.2 #LightYellow
usecase "<b>UC_3</b>\nАвторизація" as UC_3 #LightYellow
usecase "<b>UC_4</b>\nПерегляд\nквитка" as UC_4 #LightYellow
usecase "<b>UC_5</b>\nПерегляд\nпридбаних квитків" as UC_5 #LightYellow
usecase "<b>UC_6</b>\nПерегляд продажів\nна маршрутах" as UC_6 #LightYellow
usecase "<b>UC_7</b>\nСтворення і зміна\nмаршрутів" as UC_7 #LightYellow
usecase "<b>UC_8</b>\nЗміна\nзнижок" as UC_8 #LightYellow

User --> UC_1
User --> UC_2
User -> UC_3
User -u-> UC_4
User -l-> UC_5

UC_1 ..> UC_1.1: extends
UC_1 ..> UC_1.2: extends
UC_2 .> UC_1: include

Admin --|> User

Admin -u->UC_6
Admin -u->UC_7
Admin -u->UC_8
right footer
    Програмний продукт для складання подорожей.
    Дiаграма прецедентiв.
    НТУУ КПІ ім.І.Сікорського
    Голубов Iван
    Київ-2023
end footer

@enduml